config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants do
    resources :reviews, only: %i(new create)
  end
  # resources :reviews, only: [:destroy, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian)}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, less_than_or_equal_to: 5, greater_than_or_equal_to: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]
  def index
    @restaurants = Restaurant.all
    # raise
  end

  def show; end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show]
  before_action :set_restaurant, only: [:create, :new]
  def index
    @reviews = Review.all
    # raise
  end

  def show; end

  def new
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.new(review_params)
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content, :restaurant)
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to "Restaurants", restaurants_path, class: "btn btn-light" %>
      <%= link_to "Create a New Restaurant", new_restaurant_path, class: "btn btn-light" %>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_list.html.erb
<% restaurants.each do |restaurant| %>
  <h3><%= restaurant.name %></h3>
  <p>
    <%= link_to "Show this restaurant", restaurant %>
  </p>
<% end %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
  <h4><%= restaurant.name %></h4>
  <p><strong>Address: </strong><%= restaurant.address %> </p>
  <p><strong>Phone number: </strong><%= restaurant.phone_number %> </p>
  <p><strong>Category: </strong><%= restaurant.category.capitalize %> </p>
  <p>
    <%= link_to "Show this restaurant", restaurant %>
  </p>
<% end %>
</div>

app/views/restaurants/new.html.erb
<h1>Add a new restaurant</h1>

<%= simple_form_for(@restaurant) do |f| %>
  <!-- [...] -->
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: ["chinese", "italian", "japanese","french", "belgian"] %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><strong>Address: </strong><%= @restaurant.address %> </p>
<p><strong>Phone number: </strong><%= @restaurant.phone_number %> </p>
<p><strong>Category: </strong><%= @restaurant.category.capitalize %> </p>
<p><strong>Reviews: </strong>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li><%= "⭐️" * review.rating %>
          <p><%= review.content %></p>
      </li>
    <% end %>
  </ul>
</p>

<p>
  <%= link_to "Back", restaurants_path, class: "btn btn-primary"%>
  <%= link_to "Add a new review", new_restaurant_review_path(@restaurant), class: "btn btn-primary"%>
</p>

app/views/reviews/new.html.erb
<h1>Create a new review for this restaurant</h1>


<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, collection: ["0", "1", "2", "3", "4", "5"] %>
  <%= f.input :content %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>